# Site
name: "Anthony Zhou"
title: "Anthony Zhou"
description: "Psychology, Economics, Programming, or anything interesting. Updated Weekly."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-155734640-1'
disqus: 'anthonyzhou'
mailchimp-list: 'https://anthonyzhou.us4.list-manage.com/subscribe/post?u=5a6e7d003b2fa5aa5a64c2b43&amp;id=6caec32f58" method="post" id="mc-embedded-subscribe-form'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  anthony:
    name: Anthony Zhou
    display_name: Anthony Zhou
    gravatar: 5e2d9c4831fea6196ab6e552ae857d08
    email: azhou.blog@gmail.com
    web: https://anthonyzhou.me
    twitter: https://twitter.com/Anthony97655896
    description: "Blog author and computer science enthusiast. In my free time, I enjoy reading, playing the trumpet and rock climbing."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
